[package]
authors = ["gaoxiaojun"]
edition = "2018"
name = "rzen"
version = "0.1.0"

[dependencies]
chrono = "*"
plotly = {version = "0.6.0", features = ["kaleido"]}
serde = "*"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
csv = "1.1"
